apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-lab-app
  labels:
    app: docker-lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-lab-app
  template:
    metadata:
      labels:
        app: docker-lab-app
    spec:
      containers:
        - name: api
          image: docker-lab-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: APP_VERSION
              value: "k8s"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-lab-app
spec:
  selector:
    app: docker-lab-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
